language: ruby
sudo: required
dist: trusty
install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update
  - "sudo apt-get install -y gawk wget git-core diffstat unzip texinfo \
  gcc-multilib build-essential chrpath socat libsdl1.2-dev \
  libsdl1.2-dev xterm sed cvs subversion \
  coreutils texi2html docbook-utils python-pysqlite2 help2man gcc \
  g++ make desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev \
  mercurial autoconf automake groff curl lzop asciidoc u-boot-tools"
env:
  matrix:
   - DEFCONFIG_NAME=arcturus_ucls1012a_defconfig
script:
- echo 'Getting "repo" tool'
- mkdir -p ~/bin
- curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
- chmod a+x ~/bin/repo
- PATH=${PATH}:~/bin
- echo 'Getting Yocto code'
- mkdir -p fsl-arm-yocto-bsp
- cd fsl-arm-yocto-bsp
- git config --global color.ui true
- repo init -u https://source.codeaurora.org/external/imx/imx-manifest -b imx-linux-sumo -m imx-4.14.78-1.0.0_machinelearning.xml
- repo sync
- echo 'Building fsl-image-qt5'
- EULA=1 MACHINE=imx8qmmek DISTRO=fsl-imx-xwayland source ./fsl-setup-release.sh -b bld-wayland
- echo "BBLAYERS += \" \${BSPDIR}/sources/meta-imx-machinelearning \"" >> conf/bblayers.conf
- bitbake fsl-image-qt5