version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:xenial

    steps:
      - checkout

      - run:
          name: Install Required Packages
          command: |
            sudo apt-get update
            sudo apt-get install -y gawk wget git-core diffstat unzip texinfo
            sudo apt-get install -y gcc-multilib build-essential chrpath socat libsdl1.2-dev
            sudo apt-get install -y libsdl1.2-dev xterm sed cvs subversion
            sudo apt-get install -y coreutils texi2html docbook-utils python-pysqlite2 help2man gcc
            sudo apt-get install -y g++ make desktop-file-utils libgl1-mesa-dev libglu1-mesa-dev
            sudo apt-get install -y mercurial autoconf automake groff curl lzop asciidoc u-boot-tools
            sudo apt-get install -y cpio
            sudo apt-get install locales
            sudo dpkg-reconfigure locales
            sudo locale-gen en_US.UTF-8
            sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
            mkdir -p ~/bin
            curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
            chmod a+x ~/bin/repo
            export PATH=${PATH}:~/bin

      - run:
          name: Download and set up yocto-imx-machine-learning code
          command: |
            export PATH=${PATH}:~/bin
            export LANG=en_US.UTF-8
            mkdir -p fsl-arm-yocto-bsp
            cd fsl-arm-yocto-bsp
            git config --global user.name hmahadik
            git config --global user.email harshad@arcturusnetworks.com
            git config --global color.ui true
            repo init -u https://source.codeaurora.org/external/imx/imx-manifest -b imx-linux-sumo -m imx-4.14.98-2.0.0_machinelearning.xml
            repo sync
            EULA=1 MACHINE=imx8qmmek DISTRO=fsl-imx-xwayland source ./fsl-setup-release.sh -b bld-wayland
            echo "BBLAYERS += \" \${BSPDIR}/sources/meta-imx-machinelearning \"" >> conf/bblayers.conf

      - run:
          name: Building fsl-image-qt5
          command: |
            cd fsl-arm-yocto-bsp
            source setup-environment bld-wayland
            export LANG=en_US.UTF-8
            bitbake fsl-image-gui